var anlzSearchEngine=new Array();anlzSearchEngine.push("daum.net");anlzSearchEngine.push("nate.com");anlzSearchEngine.push("naver.com");anlzSearchEngine.push("bing.com");anlzSearchEngine.push("yahoo.com");anlzSearchEngine.push("yahoo.co.kr");anlzSearchEngine.push("google.com");anlzSearchEngine.push("google.co.kr");anlzSearchEngine.push("zum.com");var setAnlzCookie=function(key,value){var argsVal=arguments;var argsLength=arguments.length;var tempExp=(argsLength>2)?argsVal[2]:'';var tempDomain=(argsLength>3)?argsVal[3]:'';if(tempExp!==''){var date=new Date();date.setDate(date.getDate()+Number(tempExp));tempExp=date.toGMTString();document.cookie=key+'='+value+';expires='+tempExp+';domain='+tempDomain+';path=';}else{document.cookie=key+'='+value+';domain='+tempDomain+';path=';}};var delAnlzCookie=function(key,domain){document.cookie=key+'=;expires=-1'+';domain='+domain+';path=';};var getAnlzCookie=function(key){var allcookies=document.cookie;var cookies=allcookies.split('; ');for(var i=0;i<cookies.length;i++){var keyValues=cookies[i].split('=');if(keyValues[0]==key){return unescape(keyValues[1]);}}
return'';};var getAnlzSearchEngineYn=function(urlStr){if(urlStr==='')
return'N';var _hostIndex1=urlStr.indexOf('//')+2;var _hostIndex2=urlStr.substr(_hostIndex1).indexOf('/');urlStr=urlStr.substr(_hostIndex1,_hostIndex2);for(var i=0;i<anlzSearchEngine.length;i++){if(urlStr.indexOf(anlzSearchEngine[i])>=0)
return'Y';}
return'N';};var getAnlzPageViewCnt=function(){var anlzVisitCnt=getAnlzCookie(anlzSessionId);if(anlzVisitCnt==''){anlzVisitCnt=1;}
setAnlzCookie(anlzSessionId,(Number(anlzVisitCnt)+1),'',location.hostname);return anlzVisitCnt;};var checkAnlzReflash=function(url,ref){return true;};var getFirstVisitYn=function(flag){var anlzFirstVisitYn='';var visitDate=new Date();visitDate.setMinutes(0);visitDate.setSeconds(-1);var setAnlzCookie2=function(key,value){var argsVal=arguments;var argsLength=arguments.length;var tempDomain=(argsLength>2)?argsVal[2]:'';var tempExp=visitDate.toGMTString();document.cookie=key+'='+value+';expires='+tempExp+';domain='+tempDomain+';path=';};switch(flag){case'ALL':anlzFirstVisitYn=getAnlzCookie('anlzFirstVisitYn');setAnlzCookie('anlzFirstVisitYn','N',365,location.hostname);break;case'HOUR':visitDate.setHours(visitDate.getHours()+1);anlzFirstVisitYn=getAnlzCookie('anlzFirstVisitHourYn');setAnlzCookie2('anlzFirstVisitHourYn','N',location.hostname);break;case'DATE':visitDate.setDate(visitDate.getDate()+1);visitDate.setHours(0);anlzFirstVisitYn=getAnlzCookie('anlzFirstVisitDateYn');setAnlzCookie2('anlzFirstVisitDateYn','N',location.hostname);break;case'WEEK':visitDate.setDate(visitDate.getDate()+(7-visitDate.getDay()));visitDate.setHours(0);anlzFirstVisitYn=getAnlzCookie('anlzFirstVisitWeekYn');setAnlzCookie2('anlzFirstVisitWeekYn','N',location.hostname);break;case'MONTH':visitDate.setMonth(visitDate.getMonth()+1);visitDate.setDate(1);visitDate.setHours(0);anlzFirstVisitYn=getAnlzCookie('anlzFirstVisitMonthYn');setAnlzCookie2('anlzFirstVisitMonthYn','N',location.hostname);break;}
if(anlzFirstVisitYn===null||$.trim(anlzFirstVisitYn)===""){anlzFirstVisitYn='Y';}
return anlzFirstVisitYn;};var getAnlzUserId=function(){var anlzUserId=getAnlzCookie('anlzUserId');if($.trim(anlzUserId)==''){anlzUserId=anlzClientIp+'|'+(new Date()).getTime();setAnlzCookie('anlzUserId',anlzUserId,365,location.hostname);}
return anlzUserId;};var getAnlzReVisitPeriod=function(){var AnlzReVisitPeriod=0;var anlzLastVisitDt=getAnlzCookie('anlzLastVisitDt');anlzCurrDt=(new Date()).getTime();if($.trim(anlzLastVisitDt)!==''){AnlzReVisitPeriod=(Number(anlzCurrDt)-Number(anlzLastVisitDt))/1000/60/60/24;}
setAnlzCookie('anlzLastVisitDt',anlzCurrDt,365,location.hostname);return parseInt(AnlzReVisitPeriod);};var analyzePageLog=function(){if(checkAnlzReflash(document.location.href,document.referrer)===false){return false;}
var pageSj=$.trim($("title").text());if(pageSj==""){pageSj="제목없음";}
var _ANALYZE_PAGE_LOG_DATA={userId:getAnlzUserId(),domnNm:location.hostname,userMenuCode:anlzMenuCode,url:document.location.href,transrCours:document.referrer,userAgent:navigator.userAgent,rsoltnAr:screen.width,rsoltnHg:screen.height,scrinColorCo:screen.colorDepth,pgeSj:pageSj,frstConectrAt:getFirstVisitYn('ALL'),searchEngineInflowAt:getAnlzSearchEngineYn(document.referrer),pgeViewCo:getAnlzPageViewCnt(),frstConectHourAt:getFirstVisitYn('HOUR'),frstConectDeAt:getFirstVisitYn('DATE'),frstConectWeekAt:getFirstVisitYn('WEEK'),frstConectMtAt:getFirstVisitYn('MONTH'),againVisitPd:getAnlzReVisitPeriod()};$.ajax(VCTX_PATH+"/component/anallyze/ND_insertTracking.do",{type:'POST',data:_ANALYZE_PAGE_LOG_DATA,timeout:5000});};$(document).ready(function(){analyzePageLog();});